kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: trident-registry-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: gold
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
